[build]
  base= "client/"

# production
[context.master]
  command = "HOST=https://applicant-portal.herokuapp.com yarn build --environment=production"

# staging
[context.staging]
  command = "HOST=https://applicant-portal-staging.herokuapp.com yarn build --environment=production"

# qa team
[context.qa]
  command = "HOST=https://applicant-portal-qa.herokuapp.com yarn build --environment=production"

# develop
[context.develop]
  command = "HOST=https://applicant-portal-develop.herokuapp.com yarn build --environment=production"

