export const ZONING_MAP_CHANGE_ATTRS = [
  'versionnumber',
  'dcp_proposedzoningmapvalue',
  'statuscode',
  'overriddencreatedon',
  'modifiedon',
  'createdon',
  'statecode',
  'dcp_zoningsectionmapsnumber',
  'dcp_proposedzoningdistrictvalue',
  'dcp_changenumber',
  'importsequencenumber',
  'dcp_number',
  'utcconversiontimezonecode',
  'dcp_zoningmapchangesid',
  'dcp_existingzoningdistrictvaluenew',
  'dcp_name',
];
