name: 🚧 Check code quality
on:
    pull_request:

jobs:
  test-client:
    name:  🧪 Test client code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: client
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install dependencies
        run: yarn install --frozen-lockfile --non-interactive
        working-directory: client
      - name: build
        env:
          DISABLE_SOURCE_MAPS: true
          BROCCOLI_ENV: production
        run: yarn build
        working-directory: client
      - name: test
        run: yarn test
        working-directory: client
