name: 🎭 Deploy to production

on: workflow_dispatch
  
jobs:
    deploy-server:
        name: 🚀 Deploy server
        environment:
            name: production
            url: https://applicant-portal.herokuapp.com
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                sparse-checkout: server
            - name: Deploy server to Heroku
              uses: akhileshns/heroku-deploy@v3.13.15
              with:
                heroku_email: ${{secrets.HEROKU_EMAIL}}
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                team: ${{secrets.HEROKU_TEAM}}
                appdir: server
              env:
                HD_ADO_PRINCIPAL: ${{secrets.ADO_PRINCIPAL}}
                HD_AUTHORITY_HOST_URL: ${{secrets.AUTHORITY_HOST_URL}}
                HD_CITYPAY_AGENCYID: ${{secrets.CITYPAY_AGENCYID}}
                HD_CITYPAY_CUSTOMER_LINK: ${{secrets.CITYPAY_CUSTOMER_LINK}}
                HD_CITYPAY_DOMAIN: ${{secrets.CITYPAY_DOMAIN}}
                HD_CITYPAY_PASSWORD: ${{secrets.CITYPAY_PASSWORD}}
                HD_CITYPAY_POSTBACK: ${{secrets.CITYPAY_POSTBACK}}
                HD_CITYPAY_RETURN_FROM_CART: ${{secrets.CITYPAY_RETURN_FROM_CART}}
                HD_CITYPAY_RETURN_FROM_CHECKOUT: ${{secrets.CITYPAY_RETURN_FROM_CHECKOUT}}
                HD_CITYPAY_USERNAME: ${{secrets.CITYPAY_USERNAME}}
                HD_CLIENT_ID: ${{secrets.CLIENT_ID}}
                HD_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
                HD_CRM_HOST: ${{secrets.CRM_HOST}}
                HD_CRM_SERVICE_CONTACT_ID: ${{secrets.CRM_SERVICE_CONTACT_ID}}
                HD_CRM_URL_PATH: ${{secrets.CRM_URL_PATH}}
                HD_FIXIE_URL: ${{secrets.FIXIE_URL}}
                HD_NODE_ENV: ${{secrets.NODE_ENV}}
                HD_NYCID_SERVICE_ACCOUNT_USERNAME: ${{secrets.NYCID_SERVICE_ACCOUNT_USERNAME}}
                HD_NYCID_TOKEN_SECRET: ${{secrets.NYCID_TOKEN_SECRET}}
                HD_PAPERTRAIL_API_TOKEN: ${{secrets.PAPERTRAIL_API_TOKEN}}
                HD_RER_FILETYPE_UUID: ${{secrets.RER_FILETYPE_UUID}}
                HD_SHAREPOINT_CLIENT_ID: ${{secrets.SHAREPOINT_CLIENT_ID}}
                HD_SHAREPOINT_CLIENT_SECRET: ${{secrets.SHAREPOINT_CLIENT_SECRET}}
                HD_SHAREPOINT_CRM_SITE: ${{secrets.SHAREPOINT_CRM_SITE}}
                HD_SHAREPOINT_TARGET_HOST: ${{secrets.SHAREPOINT_TARGET_HOST}}
                HD_TENANT_ID: ${{secrets.TENANT_ID}}
                HD_TOKEN_PATH: ${{secrets.TOKEN_PATH}}
                HD_ZAP_TOKEN_SECRET: ${{secrets.ZAP_TOKEN_SECRET}}
