name: 🎭 Deploy to staging

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: 🚀 Deploy
        environment:
            name: staging-applicants-api
            url: https://staging-applicants-api.nycplanningdigital.com
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.13.15
              with:
                heroku_email: ${{secrets.HEROKU_EMAIL}}
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                team: ${{secrets.HEROKU_TEAM}}